# @package _global_

layers: 2

problem_cls: BudgetAllocation.BudgetAllocation
problem_kwargs:
    num_train_instances: 100
    num_test_instances: 500
    val_frac: 0.2
    budget: 2
    num_items: 5
    num_targets: 10
    num_fake_targets: 0
    rand_seed: ${dataset_seed}

pred_lr: 1e-4
batchsize: 100
