# @package _global_

layers: 1

problem_cls: CubicTopK.CubicTopK
problem_kwargs:
    num_train_instances: 400
    num_test_instances: 400
    num_items: 50
    budget: 1
    rand_seed: ${dataset_seed}
    val_frac: 0.5

pred_lr: 0.1
batchsize: 50
